package Storage;

public enum EndPoint {
    GET_ALL_TASKS,
    GET_ALL_EPICS,
    GET_ALL_SUBTASKS,
    GET_TASK_BY_ID,
    GET_EPIC_BY_ID,
    GET_SUBTASK_BY_ID,
    POST_NEW_TASK,
    POST_NEW_EPIC,
    POST_NEW_SUBTASK,
    POST_UPDATED_TASK,
    POST_UPDATED_EPIC,
    POST_UPDATED_SUBTASK,
    DELETE_TASK,
    DELETE_EPIC,
    DELETE_SUBTASK,
    DELETE_ALL_TASKS,
    GET_ALL_SUBTASKS_OF_ONE_EPIC,
    GET_PRIORITISED_TASKS,
    GET_HISTORY, //3
    UNKNOWN
}
